export {default as Customization} from "./Customization"
export {default as Hero} from "./Hero"
export {default as Header} from "./Header"
export {default as Categories} from "./Categories"
export {default as Body} from "./Body"
export {default as Items} from "./Items"
export {default as SubscribeBottom} from "./SubscribeBottom"
export {default as Pricings} from "./Pricings"
